### ISSUE TITLE
Creating a new datarequest throws an internal server error on the brower

### ISSUE THREAD

**Issue by andela-onnenanya** [CodeForAfricaLabs/ckanext-datarequests#2]
### Bug:
In `/datarequests/new`, after filling the datarequest form, when a user clicks on Create Data Request, an Internal Server Error page is displayed.

#### Browser Mode:
![image](https://user-images.githubusercontent.com/26964897/30240627-e98cb2b0-956b-11e7-8e01-e0a7b48ff47f.png)

#### Debug Mode:
![image](https://user-images.githubusercontent.com/26964897/30240660-80277bec-956c-11e7-9d3a-981692716d31.png)

#### Console Logs:
`Error - <type 'exceptions.AttributeError'>: 'module' object has no attribute 'redirect'
URL: http://127.0.0.1:5000/datarequest/new
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/Users/andeladeveloper/ckan/lib/default/src/ckan/ckan/config/middleware/pylons_app.py', line 245 in inner
  result = application(environ, start_response)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py', line 156 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/Users/andeladeveloper/ckan/lib/default/src/ckan/ckan/config/middleware/common_middleware.py', line 80 in __call__
  return self.app(environ, start_response)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/Users/andeladeveloper/ckan/lib/default/src/ckan/ckan/lib/base.py', line 212 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/local/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/Users/andeladeveloper/ckan/lib/default/lib/python2.7/site-packages/ckanext_datarequests-0.3.2-py2.7.egg/ckanext/datarequests/controllers/ui_controller.py', line 203 in new
  self._process_post(constants.DATAREQUEST_CREATE, context)
File '/Users/andeladeveloper/ckan/lib/default/lib/python2.7/site-packages/ckanext_datarequests-0.3.2-py2.7.egg/ckanext/datarequests/controllers/ui_controller.py', line 177 in _process_post
  base.redirect(helpers.url_for(controller='ckanext.datarequests.controllers.ui_controller:DataRequestsUI',
AttributeError: 'module' object has no attribute 'redirect'`

**Comment by andela-pijege** [comment]
I am having the same issue; `Internal Server Error`. Not only on creating data requests, but also in several other places where the user should be redirected to another page after executing a given action. For example; in `Updating the data requests`.

**Comment by andela-onnenanya** [comment]
When I go back to `/datarequest`, I see that the data request has been created

**Comment by NaiRobley** [comment]
Same thing happens when I click on my profile or try to log out

**Comment by DavidLemayian** [comment]
@andela-onnenanya I am unable to replicate this issue.

**Comment by andela-onnenanya** [comment]
@DavidLemayian You are right. I saw [here](https://africaopendata.org/api/util/status) that you are currently using CKAN-2.5.4 for the site [africaopendata](https://africaopendata.org/api/util/status).
With CKAN-2.5.4, ckanext-datarequest works well, but in the latest version of CKAN (We use 2.7.0a), a lot of things are broken. 

I am of the opinion that this may be the right time to release a new version of ckanext-datarequest.

**Comment by DavidLemayian** [comment]
@andela-onnenanya Yeah, let's have it work for https://github.com/CodeForAfricaLabs/openAFRICA (v2.6.x) and go from there.
