### ISSUE TITLE
[Feature] Add 'edit' and 'delete' functionality in data request comments

### ISSUE THREAD

**Issue by andela-pijege** [CodeForAfricaLabs/ckanext-datarequests#8]
As a user, when I add a comment on a data request, I should be able to edit or delete the comment.

**Comment by DavidLemayian** [comment]
@andela-pijege But you are able to do this already. I deleted the test ones on openAFRICA.net already. Unless I don't understand what you mean?

**Comment by andela-pijege** [comment]
Ok, i just confirmed it. I think the problem is me using a higher version of ckan. Thanks for the clarification.
